
<section id="section-inclurProduto" class="col-md-12">
        <form  class="col-md-12" id="inclurProduto-form" class="form-horizontal" method="POST">

            <fieldset>



                <!-- Form Name -->

                <legend><strong>Cadastro de  produtos</strong></legend>



                <!-- Text input-->


                <div class="col-md-6" class="form-group">


                    <label class="col-md-12 control-label" for="codigo">Codigo</label>

                    <div class="col-md-12">

                        <input id="codigo" name="codigo" type="text" placeholder="Codigo produto" class="form-control input-md">

                    </div>

                </div>



                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="agenteExtintor">Agente Extintor</label>

                    <div class="col-md-12">

                        <input id="agenteExtintor" name="agenteExtintor" type="text" placeholder="Agente Extintor" class="form-control input-md" >

                    </div>

                </div>

                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="capacidadeExtintora">Capacidade Extintora</label>

                    <div class="col-md-12">

                        <input id="capacidadeExtintora" name="capacidadeExtintora" type="text" placeholder="Capacidade Extintora" class="form-control input-md">

                    </div>

                </div>




                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="Carga">Carga</label>

                    <div class="col-md-12">

                        <input id="carga" name="carga" type="text" placeholder="Carga" class="form-control input-md">

                    </div>

                </div>


                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="validadeSelo">Validade Selo</label>

                    <div class="col-md-12">

                        <input  id="validadeSelo" name="validadeSelo" type="text" placeholder="Validade Selo"   class="form-control input-md data" >

                    </div>

                </div>



                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="dataReteste">Data reteste</label>

                    <div class="col-md-12">

                        <input id="dataReteste" name="dataReteste" type="text" placeholder="Data reteste" class="form-control input-md data" >

                    </div>

                </div>


                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="valorUnitario">Valor</label>

                    <div class="col-md-12">

                        <input id="valorUnitario" name="valorUnitario" type="text" placeholder="Valor Unitario" class="form-control input-md">

                    </div>

                </div>

                <!-- Text input-->

                <div class="col-md-6" class="form-group">

                    <label class="col-md-12 control-label" for="compra">Valor de compra</label>

                    <div class="col-md-12">

                        <input id="inclurProduto-compra" name="inclurProduto-compra" type="text" placeholder="Valor de compra" class="form-control input-md">

                    </div>

                </div>

                <!-- Button (Double) -->

                <div class="form-group">

                    <label class="control-label" for="enviar"></label>

                    <button  type="submit" value="Cadastrar"  class="btn btn-primary" > Cadastrar </button>
                </div>

            </fieldset>

            <form class="form-horizontal">
</section>

