    <legend><strong>Busca por produtos</strong></legend>

    <form class="form-horizontal" method="POST" >

        <!-- Text input-->

        <div class="col-md-4"" class="form-group">

            <label class="col-md-4 control-label" for="codigo">Codigo</label>

            <div class="col-md-8">

                <input id="codigo" name="codigo" placeholder="Busca por codigo" class="form-control input-md" type="text">

            </div>

        </div>

        <!-- Text input-->

        <div class="col-md-4" class="form-group">

            <label class="col-md-4 control-label" for="Capacidade Extintora">Capacidade Extintora</label>

            <div class="col-md-8">

                <input id="capacidadeExtintora" name="capacidadeExtintora" placeholder="Busca por Capacidade" class="form-control input-md" type="text">

            </div>

        </div>

        <!-- Text input-->

        <div class="col-md-4" class="form-group">

            <label class="col-md-4 control-label" for="dataReteste">Data Reteste</label>

            <div class="col-md-8">

                <input id="dataReteste" name="dataReteste" placeholder="Busca por Data Reteste" class="form-control input-md" type="text">

            </div>

        </div>

        <!-- Button -->

        <div class="form-group">

            <label class="col-md-12" class="control-label" for="buscar"></label>

            <button type="button" id="pesqProd" name="Pesquisar" value="vizualizar"  class="btn btn-primary" > Pesquisar  </button>
        </div>

    </form>

    <h2>Resultados da pesquisa:</h2>

    <div class="table-responsive">
        <table  id="tabProd" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
            <tr >

                <th>Codigo</th>
                <th>Agente Extintor</th>
                <th>Capacidade Extintora</th>
                <th>Carga</th>
                <th>Operações</th>
            </tr>
            </thead>
            <tbody>

                <?php foreach ($this->resultSet as $result) { ?>
                        <tr>
                            <td><?php echo $result['codigo'] ?></td>
                            <td><?php echo $result['agenteExtintor'] ?></td>
                            <td><?php echo $result['capacidadeExtintora'] ?></td>
                            <td><?php echo $result['carga'] ?></td>
                            <td>
                                <button class="btn btn-danger btn-xs" type="submit">Remover</button>
                                <button class="btn btn-success btn-xs" type="submit">Visualizar</button>
                                <button class="btn btn-primary btn-xs" type="submit">Copiar</button>
                            </td>
                        </tr>
                <?php } ?>
            </tbody>

        </table>

    </div>

