<!-- Form Name -->
<legend><strong>Cadastrar cliente</strong></legend>

<form id="cliente" class="form-horizontal" action="#" method="POST">

    <fieldset>

        <div class="col-md-12 cliente">

            <div class="col-md-4" class="form-group">


                <label class="col-md-1 control-label" for="documento">Documento</label>

                <div class="col-md-12">

                    <input id="documento" name="documento"  type="text"   value="<?php echo $this->resultSet['documento'];?>" placeholder="CPF/CNPJ" class="form-control input-md" >

                </div>

            </div>






            <!-- Text input-->

            <div class="col-md-4" class="form-group">

                <label class="col-md-1 control-label" for="nome">Nome</label>

                <div class="col-md-12">

                    <input id="nome" name="nome" type="text" value="<?php echo $this->resultSet['nome'];?>" placeholder="Nome\Fantasia" class="form-control input-md">

                </div>

            </div>



            <!-- Text input-->

            <div class="col-md-4" class="form-group">

                <label class="col-md-1 control-label" for="razaoSocial">R.Social</label>

                <div class="col-md-12">

                    <input id="razaoSocial" name="razaoSocial" type="text" value="<?php echo $this->resultSet['razaoSocial'];?>" placeholder="Razão Social" class="form-control input-md">

                </div>

            </div>
        </div>

        <div class="col-md-12 cliente">
            <!-- Text input-->

            <div class="col-md-2" class="form-group">

                <label class="col-md-1 control-label" for="inscricaoEstadual">IE</label>

                <div class="col-md-12">

                    <input id="inscricaoEstadual" name="inscricaoEstadual" type="number"  value="<?php echo $this->resultSet['inscricaoEstadual'];?>" placeholder="Inscrição Estadual" class="form-control input-md">

                </div>

            </div>


            <!-- Text input-->

            <div class="col-md-2" class="form-group">

                <label class="col-md-1 control-label" for="telefone">Tel</label>

                <div class="col-md-12">

                    <input id="telefone" name="telefone" type="number" value="<?php echo $this->resultSet['telefone'];?>" placeholder="Telefone" class="form-control input-md">

                </div>

            </div>



            <!-- Text input-->

            <div class="col-md-3" class="form-group">

                <label class="col-md-1 control-label" for="email">Email</label>

                <div class="col-md-12">

                    <input type="email"  id="email" name="email"  placeholder="Email"  value="<?php echo $this->resultSet['email'];?>" class="form-control input-md" autocomplete="on">

                </div>

            </div>




            <!-- Text input-->

            <div class="col-md-2" class="form-group">

                <label class="col-md-1 control-label" for="cep">CEP</label>

                <div class="col-md-12">

                    <input id="cep" name="cep" type="cep" value="<?php echo $this->resultSet['cep'];?>" placeholder="CEP" class="form-control input-md">

                </div>

            </div>

            <!-- Text input-->

            <div class="col-md-3" class="form-group">

                <label class="col-md-1 control-label" for="Cidade">Cidade</label>

                <div class="col-md-12">

                    <input id="cidade" name="cidade" value="<?php echo $this->resultSet['cidade'];?>" placeholder="Cidade" class="form-control input-md">

                </div>

            </div>
        </div>

        <div class="col-md-12 cliente">
            <!-- Text input-->

            <div class="col-md-3" class="form-group">

                <label class="col-md-1 control-label" for="bairro">Bairro</label>

                <div class="col-md-12">

                    <input id="bairro" name="bairro" type="text"  value="<?php echo $this->resultSet['bairro'];?>" placeholder="Bairro" class="form-control input-md">

                </div>

            </div>




            <!-- Text input-->

            <div class="col-md-4" class="form-group">

                <label class="col-md-1 control-label" for="Rua">Rua</label>

                <div class="col-md-12">

                    <input id="rua" name="rua" type="text"  value="<?php echo $this->resultSet['rua'];?>" placeholder="Rua" class="form-control input-md">

                </div>

            </div>


            <!-- Text input-->

            <div class="col-md-2" class="form-group">

                <label class="col-md-1 control-label" for="numero">Numero</label>

                <div class="col-md-12">

                    <input id="numero" name="numero" type="number" value="<?php echo $this->resultSet['numero'];?>" placeholder="Numero" class="form-control input-md">

                </div>

            </div>



            <!-- Text input-->

            <div class="col-md-3" class="form-group">

                <label class="col-md-1 control-label" for="complemento">Complemento</label>

                <div class="col-md-12">

                    <input id="complemento" name="complemento" value="<?php echo $this->resultSet['complemento'];?>" placeholder="Complemento" class="form-control input-md">

                </div>
            </div>
        </div>

        <!-- Button (Double) -->

        <div class="col-md-12" class="form-group">

            <label class="control-label" for="vender"></label>

            <button  type="submit" id="cadastrarCliente" class="btn btn-primary" >Cadastrar </button>

        </div>
    </fieldset>

</form>
