<section id="section-IncluirUsuario" class="col-md-12" >


    <legend> <strong>Cadastro de usuario</strong> </legend>
    <div class="main-login" class="col-md-12">

        <form class="col-md-12"  class="form-horizontal"  method="POST">
            <fieldset   >

                <!-- Form Name -->

                <div id="msg-user-alert" class="alert alert-danger col-sm-12">
                    <span id="mensagem"></span>
                </div>
                <div  id="msg-user-sucess"class="alert alert-success">
                    <span id="mensagem-sucess"></span>
                </div>
                <!-- Text input-->
                <div  class="form-group">
                    <label class="col-md-12 control-label" for="nome">Nome</label>
                    <div  class="col-md-12">
                        <input id="nome" name="nome" type="text" placeholder="Nome" class="form-control input-md">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-12 control-label" for="usuario">Usuario</label>
                    <div class="col-md-12">
                        <input id="usuario" name="usuario" type="text" placeholder="Usuario" class="form-control input-md">

                    </div>
                </div>

                <!-- Password input-->
                <div class="form-group">
                    <label class="col-md-12 control-label" for="senha">Senha</label>
                    <div class="col-md-12">
                        <input id="senha" name="senha" type="password" placeholder="Senha" class="form-control input-md">

                    </div>
                </div>

                <!-- Text input -->
                <div class="form-group">
                    <label class="col-md-12 control-label" for="confirma">Confirmar senha</label>
                    <div class="col-md-12">
                        <input id="confirma" name="confirma" type="password" placeholder="Confirmar senha" class="form-control input-md">

                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="control-label" for="enviar"></label>
                    <button type="submit" id="cadastrar" name="cadastrar" value="cadastrar"  class="btn btn-primary" >Cadastrar</button>
                </div>
                <a id="sair" href="#"> Login </a>

            </fieldset>
        </form>

    </div>


</section>