<div id="logo" class="col-md-9" >
    <img  src="\img\logo2.JPEG" style="width:100%">
</div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Extincendio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
			<li role="presentation" class="dropdown">
                <a id="menu" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Pesquisar <span class="caret"></span>
                    <ul class="dropdown-menu">
                        <li role="presentation"><a href="/usuario/pesquisar" id="listarUsuario">Usuario</a></li>
                        <li role="presentation"><a href="/produto/pesquisar" id="listarProduto">Produtos</a></li>
                        <li role="presentation">@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                        <li role="presentation"><a href="/venda/pesquisar" id="listarCliente">Vendas</a></li>
                    </ul>
            </li>
            </div>
        </div>
    </div>
	
	 <nav class="navbar navbar-default">
        <ul class="nav nav-pills">
            <li role="presentation" class="active">@Html.ActionLink("HOME", "Index", "Home")</li>
            
            <li role="presentation" class="dropdown">
                <a id="menu" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Cadastrar <span class="caret"></span>
                    <ul class="dropdown-menu">
                        <li role="presentation"><a href="/usuario/cadastrar" id="IncluirUsuario">Usuario</a></li>
                        <li role="presentation"><a href="/produto/cadastrar" id="inclurProduto">Produto</a></li>
                        <li role="presentation"><a href="/cliente/cadastrar" id="incluirCliente">Cliente</a></li>
                    </ul>
            </li>

            <li role="presentation" class="dropdown">
                <a id="menu" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Pesquisar <span class="caret"></span>
                    <ul class="dropdown-menu">
                        <li role="presentation"><a href="/usuario/pesquisar" id="listarUsuario">Usuario</a></li>
                        <li role="presentation"><a href="/produto/pesquisar" id="listarProduto">Produtos</a></li>
                        <li role="presentation">@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                        <li role="presentation"><a href="/venda/pesquisar" id="listarCliente">Vendas</a></li>
                    </ul>
            </li>
            <li role="presentation"><a href="/venda/vender" id="sair">Vender</a></li>
            <li role="presentation"><a href="/" id="sair">Sair</a></li>
            </li>
        </ul>
    </nav>